module.exports = {
    "FETCH_AVAILABLE_TEMPLATE_ROUTE" : "/available/template",
    "FETCH_AVAILABLE_TECHSTACKS_ROUTE" : "/available/techstack",
    "FETCH_AVAILABLE_SOCIAL_LINK_TYPES_ROUTE" : "/available/sociallink",
    "FETCH_ALL_ACHIEVEMENTS_ROUTE": "/achievement/all",
    "FETCH_ACHIEVEMENT_ROUTE": "/achievement",
    "CREATE_ACHIEVEMENT_ROUTE": "/achievement",
    "UPDATE_ACHIEVEMENT_ROUTE": "/achievement",
    "DELETE_ACHIEVEMENT_ROUTE": "/achievement",
    "FETCH_ALL_CERTIFICATES_ROUTE": "/certificate/all",
    "FETCH_CERTIFICATE_ROUTE": "/certificate",
    "CREATE_CERTIFICATE_ROUTE": "/certificate",
    "UPDATE_CERTIFICATE_ROUTE": "/certificate",
    "DELETE_CERTIFICATE_ROUTE": "/certificate",
    "FETCH_ALL_EDUCATIONS_ROUTE": "/education/all",
    "FETCH_EDUCATION_ROUTE": "/education",
    "CREATE_EDUCATION_ROUTE": "/education",
    "UPDATE_EDUCATION_ROUTE": "/education",
    "DELETE_EDUCATION_ROUTE": "/education",
    "FETCH_ALL_SOCIAL_LINKS_ROUTE": "/link/all",
    "FETCH_SOCIAL_LINK_ROUTE": "/link",
    "CREATE_SOCIAL_LINK_ROUTE": "/link",
    "UPDATE_SOCIAL_LINK_ROUTE": "/link",
    "DELETE_SOCIAL_LINK_ROUTE": "/link",
    "FETCH_PROFILE_ROUTE": "/profile",
    "UPDATE_PROFILE_ROUTE": "/profile",
    "UPDATE_DOMAIN_ROUTE": "/profile/domain",
    "UPDATE_PORTFOLIO_TEMPLATE_ROUTE": "/profile/template",
    "FETCH_ALL_PROJECTS_ROUTE": "/project/all",
    "FETCH_PROJECT_ROUTE": "/project",
    "CREATE_PROJECT_ROUTE": "/project",
    "UPDATE_PROJECT_ROUTE": "/project",
    "DELETE_PROJECT_ROUTE": "/project",
    "FETCH_EXPERIENCE_ROUTE": "/experience",
    "FETCH_ALL_EXPERIENCE_ROUTE": "/experience/all",
    "UPDATE_EXPERIENCE_ROUTE": "/experience",
    "DELETE_EXPERIENCE_ROUTE": "/experience",
    "CREATE_EXPERIENCE_ROUTE": "/experience"
}